title: MarkLogic Kafka Connector
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

# Haven't needed this in other projects, but jekyll throws an error without it.
repository: "marklogic/kafka-marklogic-connector"

heading_anchors: true

logo: "/assets/ProgressMarkLogic_PrimaryLogo_Stacked.svg"

# Aux links for the upper right navigation
aux_links:
  "marklogic/kafka-marklogic-connector":
    - "https://github.com/marklogic/kafka-marklogic-connector"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

enable_copy_code_button: true
